<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn3</name>
   <tag></tag>
   <elementGuidId>496ccd07-b4b3-4c90-9d43-4a696f33ecd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span
[@id = 'select2-chosen-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-chosen-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selector</name>
      <type>Main</type>
      <value>#select2-chosen-2</value>
   </webElementProperties>
</WebElementEntity>
