<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnIngresarAnalisisEventos</name>
   <tag></tag>
   <elementGuidId>bfa2a9ac-2ba4-4cc2-871a-abfced8d8362</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Análisis</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced&quot;]/body[@class=&quot;skin-dh fixed sidebar-mini  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content content-section&quot;]/div[@class=&quot;desktop content&quot;]/div[1]/div[@class=&quot;workspace_unique&quot;]/div[@class=&quot;fieldset_wrap_uniq&quot;]/div[@class=&quot;stepwizard&quot;]/div[@class=&quot;stepwizard-row&quot;]/div[@class=&quot;stepwizard-step&quot;]/a[@class=&quot;modal_ajax_form&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
