<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>objetoPrueba</name>
   <tag></tag>
   <elementGuidId>e10daaad-0d45-4a20-bf73-a3a48d5d6c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_base_EventUnsafe_event_unsafe_5c780bbd56933_notes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
