<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPrioridadAnalisisEvento</name>
   <tag></tag>
   <elementGuidId>c76a4583-c4b2-417e-90a2-82cc30ab051c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_base_EventConductive_4_priority_id</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
