<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaDescFallasAnalisisEvento</name>
   <tag></tag>
   <elementGuidId>a13c03cf-da97-4c0f-93d7-cb6351b42b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_base_EventUnsafe_event_unsafe_5c76b5eda155c_notes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>#event_base_EventUnsafe_event_unsafe_5c76b5eda155c_notes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>event_base[EventUnsafe][event_unsafe_5c76b5eda155c][notes]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_base_EventUnsafe_event_unsafe_5c76b5eda155c_notes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_base_EventUnsafe_event_unsafe_5c76b5eda155c_notes&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#event_base_EventUnsafe_event_unsafe_5c76b5eda155c_notes</value>
   </webElementProperties>
</WebElementEntity>
