<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_event_basecontrol_not</name>
   <tag></tag>
   <elementGuidId>06ab6d3e-bdf3-4e5b-b7d7-f062f7663952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>class id(&quot;event_base_EventUnsafe_event_unsafe_5c792a48891b9_notes&quot;)[count(. | //textarea[@name = 'event_base[EventUnsafe][event_unsafe_5c792a48891b9][notes]' and @class id = 'event_base_EventUnsafe_event_unsafe_5c792a48891b9_notes']) = count(//textarea[@name = 'event_base[EventUnsafe][event_unsafe_5c792a48891b9][notes]' and @class id = 'event_base_EventUnsafe_event_unsafe_5c792a48891b9_notes'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>event_base[EventUnsafe][event_unsafe_5c792a48891b9][notes]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class id</name>
      <type>Main</type>
      <value>event_base_EventUnsafe_event_unsafe_5c792a48891b9_notes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>class id(&quot;event_base_EventUnsafe_event_unsafe_5c792a48891b9_notes&quot;)</value>
   </webElementProperties>
</WebElementEntity>
