<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>002a018e-7e7f-4845-8250-3b4e840f418d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#9EBD37</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M195.361,276.867c0,0-118.509-41.237-155.08-61.94c-16.873-9.552-35.107-16.065-35.107-59.921V35.48c0-16.968,13.755-30.723,30.723-30.723h159.463V276.867z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced&quot;]/body[@class=&quot;skin-dh fixed sidebar-mini    pace-done&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-modules&quot;]/a[@class=&quot;btn-modules-fixed no-tipsy&quot;]/svg[@class=&quot;dui-svg-clip clip-modules&quot;]/path[1]</value>
   </webElementProperties>
</WebElementEntity>
