<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_dashboardPgina de inicio</name>
   <tag></tag>
   <elementGuidId>be518538-e6fd-4cc6-a091-754e21c8738b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-sidebar__menu-root-link mat-button cdk-focused cdk-mouse-focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dashboard Página de inicio </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;ng-tns-c0-0&quot;]/mat-sidenav-container[@class=&quot;app__sidenav-container mat-drawer-container mat-sidenav-container mat-drawer-transition&quot;]/mat-sidenav[@class=&quot;app__sidenav mat-drawer mat-sidenav ng-tns-c4-8 ng-trigger ng-trigger-transform ng-tns-c0-0 ng-star-inserted mat-drawer-side app__sidenav--opened&quot;]/div[@class=&quot;mat-drawer-inner-container&quot;]/app-sidenav-content[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;app-sidebar&quot;]/mat-accordion[@class=&quot;app-sidebar__mat-accordion mat-accordion&quot;]/a[@class=&quot;app-sidebar__menu-root-link mat-button cdk-focused cdk-mouse-focused&quot;]</value>
   </webElementProperties>
</WebElementEntity>
