<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_add</name>
   <tag></tag>
   <elementGuidId>892d19ea-0977-47d3-a174-f1eb153a0f2e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon material-icons mat-icon-no-color</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;ng-tns-c0-0&quot;]/mat-sidenav-container[@class=&quot;app__sidenav-container mat-drawer-container mat-sidenav-container mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-tns-c0-0&quot;]/div[@class=&quot;app__workspace ng-tns-c0-0&quot;]/div[@class=&quot;ng-tns-c0-0 app__router-outlet-container container&quot;]/app-subjects-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-libraries-list&quot;]/app-floating-actions-buttons[1]/eco-fab-speed-dial[@class=&quot;fab-container eco-up eco-fling eco-opened&quot;]/div[@class=&quot;eco-fab-speed-dial-container&quot;]/eco-fab-speed-dial-actions[1]/button[@class=&quot;mat-mini-fab mat-accent eco-fab-action-item ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/a[@class=&quot;ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon material-icons mat-icon-no-color&quot;]</value>
   </webElementProperties>
</WebElementEntity>
